---
coverage:
  status:
    project:
      default:
        target: 70%
        removed_code_behavior: removals_only
        threshold: 5%
    patch:
      default:
        target: 50%

ignore:
  - "src/lib.rs"
