---
name: "Audit dependencies"
on:
  push:
    paths:
      # Run if workflow changes
      - .github/workflows/audit.yml
      # Run on changed dependencies
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  pull_request:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  # Rerun periodically to pick up new advisories (weekly instead of daily)
  schedule:
    - cron: '0 6 * * 1'  # Monday at 6 AM UTC
  # Run manually
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      security-events: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          cache: true
      
      - name: Cache audit database
        uses: actions/cache@v4
        with:
          path: ~/.cargo/advisory-db
          key: advisory-db-${{ github.run_id }}
          restore-keys: advisory-db-
      
      - name: Install cargo-audit
        run: cargo install --locked cargo-audit
      
      - name: Run cargo audit
        run: |
          cargo audit --json > audit-results.json || echo "Audit found issues"
          # Show human-readable output as well
          cargo audit
        continue-on-error: true
      
      - name: Upload audit results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: audit-results
          path: audit-results.json
